# -*- coding: utf-8 -*-
"""Engenharia_de_software_desafio_joao_victor_fagundi .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mQT8h3c60u_BECPDQq2JR79UK_aWmKmf
"""

!pip install --upgrade gspread

from google.colab import auth
auth.authenticate_user()

import gspread
from oauth2client.client import GoogleCredentials

gc = gspread.authorize(GoogleCredentials.get_application_default())

spreasheet = gc.open('Cópia de Engenharia de Software - Desafio_joao_victor_fagundi_d')

Engenharia_de_Software_df = ('Cópia de Engenharia de Software - Desafio_joao_victor_fagundi_d')

page = spreasheet.sheet1

page.row_values(1)

display(Engenharia_de_Software_df)

import pandas as pd
Engenharia_de_Software_df = pd.DataFrame(page.get_all_records())

#Engenharia_de_Software_df['Media']= Engenharia_de_Software_df['P1'] + ['P2'] + ['P3'] /3
display(Engenharia_de_Software_df)











print('--------------------------------------------\n')
print('bem vindo ao programa de notas\npara iniciar escolha uma das opcoes abaixo ')
print('1-Situacao\n2-Faltas\n3-Nota para Aprovacao Final\n')
print('--------------------------------------------\n')

def verifica(msg):
  ok= False
  valor= 0
  while True:
    x= int(input(msg))
    if x >=1 and x<=3:
      valor = int(x)
      ok= True
    else:
      print('ERRO! digite uma opcao valida')
    if ok:
      break
  return valor

x = verifica ('escolha uma opcao :' )
if x == 1:
  print('situacao')
if x == 2:
  print('faltas')
if x == 3: 
  print('Nota para Aprovacao Final')